[package]
name = "pancake-server"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0.18", features = ["cargo", "derive"] }
toml = "0.5.9"
serde = "1"
serde_json = "1"
serde_derive = "1"

[dev-dependencies]
